name: Monthly eBird Fetch

permissions:
  contents: write

on:
  schedule:
    - cron: "0 2 1 * *"   # 02:00 UTC on the 1st
  workflow_dispatch:

jobs:
  run-monthly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monthly pipeline
        env:
          EBIRD_API_KEY: ${{ secrets.EBIRD_API_KEY }}
        run: |
          python fetch_data.py
          
          MONTH_YEAR=$(date +"%B_%Y")
          
          python -c "from generate_map import generate_map; generate_map('$MONTH_YEAR')"
          python -c "from generate_summary import generate_summary; generate_summary('$MONTH_YEAR')"

      - name: Generate new seasonal outputs
        run: |
          python generate_summary_seasonal.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Monthly auto update"
          git push
