name: Seasonal data aggregation

on:
  schedule:
    - cron: "0 3 1 * *"   # 1st of every month at 03:00 UTC
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas geopandas shapely fiona pyproj

      - name: Build seasonal data
        run: |
          python seasons_data.py
        env:
            EBIRD_API_KEY: ${{ secrets.EBIRD_API_KEY }}
      - name: Generate seasonal maps & summaries
        run: |
          python generate_summary_seasonal.py
        env:
            EBIRD_API_KEY: ${{ secrets.EBIRD_API_KEY }}
      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated monthly + seasonal update" || echo "No changes"
          git push
